/* eslint-disable @next/next/no-img-element */
import { SignInButton, useClerk, useUser } from "@clerk/nextjs";

import { type NextPage } from "next";
import Head from "next/head";
import PostView from "~/components/PostView";
import UserWizard from "~/components/UserWizard";
import { api } from "~/utils/api";


const Home: NextPage = () => {
  const user = useUser();
  const posts = api.post.getAll.useQuery();
  const { signOut } = useClerk()
  return (
    <>
      <Head>
        <title>Emoji Twitter</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className="w-full md:max-w-2xl md:border-x border-slate-400 overflow-auto">
          <div className="border-slate-400 flex border-b py-4 px-6">
            <div className="flex justify-between min-h-[2.5rem] w-full">
              {user.isSignedIn ? (
                <>
                  <UserWizard />
                  <button
                    className="bg-slate-400 p-2 rounded-sm text-slate-950 hover:bg-slate-500"
                    onClick={() => void signOut()}
                  >
                    Sign Out
                  </button>
                </>
              )
                :
                <SignInButton mode="modal">
                  <button
                    className="bg-slate-400 p-2 rounded-sm text-slate-950 hover:bg-slate-500"
                  >
                    Sign In
                  </button>
                </SignInButton>
              }
            </div>
          </div>

          <PostView posts={posts.data} />
        </div>
      </main>
    </>
  );
};





export default Home;
