import { SignInButton, useClerk, useUser } from "@clerk/nextjs";

import { type NextPage } from "next";
import Head from "next/head";


const Home: NextPage = () => {

  const user = useUser();
  const { signOut } = useClerk()
  console.log(user);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
        {user.isSignedIn ? (
          <>
            <h1>{user.user.lastName}</h1>
            <button onClick={() => void signOut()}>Signout</button>
          </>
        ) : (<SignInButton />)}
      </main>
    </>
  );
};

export default Home;
